AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BName:
    Type: String
Resources:
  S3Bucket: 
    Type: AWS::S3::Bucket
    Properties: 
        BucketName: !Ref BName
Outputs
  BucketName:
    Value: !Ref 'S3Bucket'